In [20]:
import pandas as pd
import numpy as np

df = pd.read_csv('trends (1).csv')
df.head(5)

  location  year         category  rank  query
0   Global  2001  Consumer Brands     1  Nokia
1   Global  2001  Consumer Brands     2   Sony
2   Global  2001  Consumer Brands     3    BMW
3   Global  2001  Consumer Brands     4   Palm
4   Global  2001  Consumer Brands     5  Adobe

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26955 entries, 0 to 26954
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   location  26955 non-null  object
 1   year      26955 non-null  int64
 2   category  26955 non-null  object
 3   rank      26955 non-null  int64
 4   query     26955 non-null  object
dtypes: int64(2), object(3)
memory usage: 1.0+ MB

In [22]:
print(df.dtypes)

location    object
year         int64
category    object
rank         int64
query       object
dtype: object

In [23]:
print("Missing values:")
print(df.isnull().sum())

Missing values:
location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [24]:
print(f"Duplicate rows: {df.duplicated().sum()}")

Duplicate rows: 10

In [26]:
df.tail(5)

      location  year category  rank                query
26950  Vietnam  2020   Là Gì?     1   Virus Corona là gì
26951  Vietnam  2020   Là Gì?     2  Miễn thị thực là gì
26952  Vietnam  2020   Là Gì?     3    Đầu cắt moi là gì
26953  Vietnam  2020   Là Gì?     4  Bệnh bạch hầu là gì
26954  Vietnam  2020   Là Gì?     5       Đông Lào là gì

In [30]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.describe()

               year   trend_rank
count  26945.000000  26945.00000
mean    2015.241974      3.00000
std        3.564557      1.41424
min     2001.000000      1.00000
25%     2013.000000      2.00000
50%     2016.000000      3.00000
75%     2018.000000      4.00000
max     2020.000000      5.00000

In [34]:
df.shape

(26945, 5)

In [36]:
df.columns

Index(['location', 'year', 'category', 'rank', 'query'], dtype='object')

In [37]:
df.isnull().sum()

location    0
year        0
category    0
rank        0
query       0
dtype: int64

In [40]:
df.nunique()

location       83
year           20
category     2446
rank            5
query       18431
dtype: int64

In [42]:
df.sum()

location    GlobalGlobalGlobalGlobalGlobalGlobalGlobalGlob...
year                                                 54300695
category    Consumer BrandsConsumer BrandsConsumer BrandsC...
rank                                                    80835
query       NokiaSonyBMWPalmAdobeNostradamusOsama bin Lade...
dtype: object

In [43]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
26940    False
26941    False
26942    False
26943    False
26944    False
Length: 26945, dtype: bool

In [44]:
df.to_csv('cleaned_trends.csv', index=False) 
print("Cleaned dataset saved!")

Cleaned dataset saved!